# Generated by Django 5.1.4 on 2025-01-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('campaign', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
